apiVersion: v1
items:
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2024-06-26T19:20:41Z"
    generation: 1
    labels:
      app: akhq
      pod-template-hash: 5887bb7b6b
    name: akhq-5887bb7b6b
    namespace: kafka
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: akhq
      uid: 3879a003-f223-4fb8-bf02-ce37f83240fb
    resourceVersion: "87963"
    uid: ecc69c3b-1959-4e6b-9f4a-a4d833c8bdd0
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: akhq
        pod-template-hash: 5887bb7b6b
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: akhq
          pod-template-hash: 5887bb7b6b
      spec:
        containers:
        - env:
          - name: MICRONAUT_CONFIG_FILES
            value: file:/config/application.yml
          image: tchiotludo/akhq:latest
          imagePullPolicy: Always
          name: akhq
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /config
            name: config-volume
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: akhq-config
          name: config-volume
  status:
    availableReplicas: 1
    fullyLabeledReplicas: 1
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
kind: List
metadata:
  resourceVersion: ""
