apiVersion: v1
items:
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2024-06-30T18:25:54Z"
    generation: 1
    labels:
      app: spring-boot-app
      pod-template-hash: 5b748dd5ff
    name: spring-boot-app-5b748dd5ff
    namespace: greetings-app
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: spring-boot-app
      uid: 037ea504-62b5-4a4f-8530-bf58c53cb4e8
    resourceVersion: "98177"
    uid: cf246d49-78bd-4535-b008-e113643d6cce
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: spring-boot-app
        pod-template-hash: 5b748dd5ff
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: spring-boot-app
          pod-template-hash: 5b748dd5ff
      spec:
        containers:
        - image: modock93/greetings-app:latest
          imagePullPolicy: Always
          name: spring-boot-app
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    fullyLabeledReplicas: 1
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
kind: List
metadata:
  resourceVersion: ""
