apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2024-06-30T16:26:51Z"
    labels:
      app: istiod
      install.operator.istio.io/owning-resource: installed-state
      install.operator.istio.io/owning-resource-namespace: istio-system
      istio: pilot
      istio.io/rev: default
      operator.istio.io/component: Pilot
      operator.istio.io/managed: Reconcile
      operator.istio.io/version: 1.22.2
      release: istio
    name: istiod
    namespace: istio-system
    resourceVersion: "87605"
    uid: 19c38771-7b1d-479d-9e0e-2920840c862b
  spec:
    clusterIP: 10.43.92.169
    clusterIPs:
    - 10.43.92.169
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: grpc-xds
      port: 15010
      protocol: TCP
      targetPort: 15010
    - name: https-dns
      port: 15012
      protocol: TCP
      targetPort: 15012
    - name: https-webhook
      port: 443
      protocol: TCP
      targetPort: 15017
    - name: http-monitoring
      port: 15014
      protocol: TCP
      targetPort: 15014
    selector:
      app: istiod
      istio: pilot
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2024-06-30T16:27:03Z"
    labels:
      app: istio-egressgateway
      install.operator.istio.io/owning-resource: installed-state
      install.operator.istio.io/owning-resource-namespace: istio-system
      istio: egressgateway
      istio.io/rev: default
      operator.istio.io/component: EgressGateways
      operator.istio.io/managed: Reconcile
      operator.istio.io/version: 1.22.2
      release: istio
    name: istio-egressgateway
    namespace: istio-system
    resourceVersion: "87684"
    uid: 0ef22fff-53ed-45e9-bde7-831741b0bf22
  spec:
    clusterIP: 10.43.165.219
    clusterIPs:
    - 10.43.165.219
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
    selector:
      app: istio-egressgateway
      istio: egressgateway
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2024-06-30T16:27:03Z"
    finalizers:
    - service.kubernetes.io/load-balancer-cleanup
    labels:
      app: istio-ingressgateway
      install.operator.istio.io/owning-resource: installed-state
      install.operator.istio.io/owning-resource-namespace: istio-system
      istio: ingressgateway
      istio.io/rev: default
      operator.istio.io/component: IngressGateways
      operator.istio.io/managed: Reconcile
      operator.istio.io/version: 1.22.2
      release: istio
    name: istio-ingressgateway
    namespace: istio-system
    resourceVersion: "87699"
    uid: 4a093f46-6c10-4956-a900-b74ec8c5635b
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 10.43.185.213
    clusterIPs:
    - 10.43.185.213
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: status-port
      nodePort: 31549
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http2
      nodePort: 32310
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      nodePort: 31235
      port: 443
      protocol: TCP
      targetPort: 8443
    - name: tcp
      nodePort: 32745
      port: 31400
      protocol: TCP
      targetPort: 31400
    - name: tls
      nodePort: 32178
      port: 15443
      protocol: TCP
      targetPort: 15443
    selector:
      app: istio-ingressgateway
      istio: ingressgateway
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
