apiVersion: v1
items:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"notifications-controller","app.kubernetes.io/name":"argocd-notifications-controller","app.kubernetes.io/part-of":"argocd"},"name":"argocd-notifications-secret","namespace":"argocd"},"type":"Opaque"}
    creationTimestamp: "2024-06-30T18:23:47Z"
    labels:
      app.kubernetes.io/component: notifications-controller
      app.kubernetes.io/name: argocd-notifications-controller
      app.kubernetes.io/part-of: argocd
    name: argocd-notifications-secret
    namespace: argocd
    resourceVersion: "93423"
    uid: 3931d92c-3d6a-4393-8489-7b4e29616895
  type: Opaque
- apiVersion: v1
  data:
    auth: ZmphVlhKeGFySmpMMFI3MA==
  kind: Secret
  metadata:
    creationTimestamp: "2024-06-30T18:24:28Z"
    name: argocd-redis
    namespace: argocd
    resourceVersion: "93626"
    uid: 3bd85064-eaf7-4423-a501-71614fe49c83
  type: Opaque
- apiVersion: v1
  data:
    password: RjZIZEl5NUd6QXFoWnpXeA==
  kind: Secret
  metadata:
    creationTimestamp: "2024-06-30T18:24:29Z"
    name: argocd-initial-admin-secret
    namespace: argocd
    resourceVersion: "93639"
    uid: 819b8a04-a21b-436b-b975-d96a99fafcfc
  type: Opaque
- apiVersion: v1
  data:
    admin.password: JDJhJDEwJG0wcS9yc3dUZ3dpSjdFLjRtUnRPOC54Q2FZTHVlQUpNRU1GWXdxRkVGMURzakphRDZxZ2U2
    admin.passwordMtime: MjAyNC0wNi0zMFQxODoyNDoyOVo=
    server.secretkey: QXVleDh2WVNqcGRyM3l6ZmtKQVZGNGlVdDdCS1RzdmlOclkzSzkxZVdDQT0=
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURZakNDQWtxZ0F3SUJBZ0lRVE9LMk5QNmFWYXFrRFd5MlNmZkVtekFOQmdrcWhraUc5dzBCQVFzRkFEQVMKTVJBd0RnWURWUVFLRXdkQmNtZHZJRU5FTUI0WERUSTBNRFl6TURFNE1qUXpNRm9YRFRJMU1EWXpNREU0TWpRegpNRm93RWpFUU1BNEdBMVVFQ2hNSFFYSm5ieUJEUkRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQUsyOVRGSTJYWkVIR0ZRQWFSTnlmc2szZkVUd2UxQUlzVnowTE4zemU3WDh3RVdpWnB3WVErQ20KWE8yMVZ3TEdzZmN4dDZaOHVFS3piTjhrRnA4NDE5VjJGR2lxeUNIckFaRU04SXJzNHp2a0ZQV1JxZ3piMTBvbwpKdUJGSDV1S2ViOGxaeVJMa1pYSFhKS0ptYTh4TVJMUDkwL2dxcmRpZ083Wnk1eUdJTlRNMU9HNnpMNWk5RmhKCkNHLytYZnVNdjNDNWEwbml6OENmcTFQTnBEWFhkcFpIZ1JkQmhUTXBqUmVyRnlhckZpMVJNZFAvT0d5ZVArNHEKbTB6Z3E4M3BNdFRZYmErL2lhRXFkN0hTSUpHK09XSStOYTJQNG5qZTB3ZmtUVTlBQlAyQml2Y2U5STU0OTdvQQp3MDh2SnlOMkRSVjd5dmlUTjVTTldGTEhLMHZyMVc4Q0F3RUFBYU9Cc3pDQnNEQU9CZ05WSFE4QkFmOEVCQU1DCkJhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUhBd0V3REFZRFZSMFRBUUgvQkFJd0FEQjdCZ05WSFJFRWREQnkKZ2dsc2IyTmhiR2h2YzNTQ0RXRnlaMjlqWkMxelpYSjJaWEtDRkdGeVoyOWpaQzF6WlhKMlpYSXVZWEpuYjJOawpnaGhoY21kdlkyUXRjMlZ5ZG1WeUxtRnlaMjlqWkM1emRtT0NKbUZ5WjI5alpDMXpaWEoyWlhJdVlYSm5iMk5rCkxuTjJZeTVqYkhWemRHVnlMbXh2WTJGc01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ09lL2ptdWpNNXpmMjcKQ1ZLekdWTmJlRk9QV0tpc1ArRDcvMHg2Nlh5ZWduQTZia3lwaTIxK3JKZUpjS1MxemVyOHR2S2xoMVhmanRsMwp5VUVPTTFId2EycSs5NkNPaGhsVDRJMGdlR1JOYzRaL2NlV2pkS3ZYZGd3SzB6TWYxbHZmZ091ZVZ6VnZ6aUtiClkvODBDUFQ1ZjRNbSsyYVF2RXoxUDBjek00b0g2RFZ4VFZRL2hHS1A5Z1hVVGJ0UnljNDlhUVZCdDl6aTNiUncKU1N0M2F1Zi9GY3BReDl2dmtqV09HVGJPRGhUNk91NFJnTnBKSTlJejJkZStuVDhSN1NPaTdIYzBUdVVWejVJMwpxR0hEdHgxbThpMG5uK0I3aCtmK1MvRkRwL0N4UmRIaHM4dkVvcTRiR2ljYXEzVUtpOG5WQWI3QnJWZlUrcU1sCkNhM0VTUDlZCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBcmIxTVVqWmRrUWNZVkFCcEUzSit5VGQ4UlBCN1VBaXhYUFFzM2ZON3RmekFSYUptCm5CaEQ0S1pjN2JWWEFzYXg5ekczcG55NFFyTnMzeVFXbnpqWDFYWVVhS3JJSWVzQmtRendpdXpqTytRVTlaR3EKRE52WFNpZ200RVVmbTRwNXZ5Vm5KRXVSbGNkY2tvbVpyekV4RXMvM1QrQ3F0MktBN3RuTG5JWWcxTXpVNGJyTQp2bUwwV0VrSWIvNWQrNHkvY0xsclNlTFB3SityVTgya05kZDJsa2VCRjBHRk15bU5GNnNYSnFzV0xWRXgwLzg0CmJKNC83aXFiVE9Dcnpla3kxTmh0cjcrSm9TcDNzZElna2I0NVlqNDFyWS9pZU43VEIrUk5UMEFFL1lHSzl4NzAKam5qM3VnRERUeThuSTNZTkZYdksrSk0zbEkxWVVzY3JTK3ZWYndJREFRQUJBb0lCQUM5MEFLQ0QwTktIeVpGSAorMnNnWHBpKzJ1WkplS1RIZXdvVWR4eTRJQlg0enRzMkhDaU9TQnZYMUpIb2NiZUVaWjlLcVFxRURoL0p1ZmJJCmVKVk1oVWI4VlY2eEpyQjg2NVNlb0NTUnh3N1lvUkRobER5bTN3cVdKT2drZVJtV25PSWthU04wc0hMa1hOaDUKVk15UTl3SllZd2dpS1A2bG5PbWYrd2pwYVpZMVdHMkJMdWhTNm4yUlNJRDJ1MTN0U0dDSzkwN09DdjZrem9VdwpSN3FmQmVoVGFQNEJ1ODRScGRIMzdjTDM2Q1FsZXZvdVMyU0ZrNVlLMThPRjlEcnNsTEZzN3IxM1l2OWtyWmovClF1RnJodXhZQTRrKzdHeTZaL29tTUN6a05YRmVoVjQ0U2hrR0VqRllOMnY0dmViNlJPYmFTQ2tFTkhKNSs0bHcKTTIrM2xVRUNnWUVBd3I0RnBvVXAxclBXazE2elQ3d09ScFRGNjR0NFBiN1djdmZ4MVRmTzE5UE1VZEY5QWZSKwpFSktaVnlqOUk5dm9pamdmM00weFBJSXBHUEJPSEZDc3RNTmtRSG1WWHNzSS8vVjR1dkx1RkM0TTYrUmFKa0JUCkVuRUxDTVFSbTFnOUJVVVVyY0t0dFZibnA4OGdnYmsyNHo5aTBmQkZFNUZLcFVoT3JQQ29ZV2tDZ1lFQTVHUDgKSXc0OEc0VFFwYWsrd0dGWjRsSitLNUZDeVRPZHExRFZ1MFdQVlpvRVo1blNqMExUUHlSNnVtYUQrRFdqN3ZOUwp4MDE5OGV3T2xXOVB6Y1pWdWVDd3daSkxWekJvVlNpdnVUOHZyUFVOTVVpUzlWRnlrajV1OGNkYmRVc05uekwxCjJXWG9DNllOZThiREtlam1ZVjQwTjZCcG90dmVHZWdtZ1AwNnpSY0NnWUVBbmYydDlkL1pCcS9XS0s5T3lDUm8KYklpc1hhRkVCc3Y1alVKc3R5L1VwckxVODVnQ1ZBQzMrZGdGZ1hubWpSNE85WHY5RlpSL0duajZ3Sm5NdFJvYQpVM2lscjgwMENyaXI3NFNGMHgzZFd3L1ZPZGVENzc2RjV0TkJRWFpZVm5CcTZRaVhjelVhMnFETHhnKzdicU1GCnphMlNEWUpoZURPS25MY2g1UnBGY09rQ2dZQXdpTXJoRERwYndycXdLYW9yS2NUM0luNnJkWUFTejhRMnpzUE0KdXpoOWdYQmtMNzBlTXA0L3NkbmUyTUE4cy9GMWF3SHhWcGRvSExqd3FxbnoyYTBJQmlhcHpCUDBvRlhibXZ6VQp5Z2V3b3BhK0hXVVZlc3gxSlkxZ0ZmUnFsWnQ4ZEZEb2RRNTl3emprVDlYVGh5bkdFVVhaZUY1YWZJelRScEZBCkloQW4yd0tCZ0RrRWtWSWNyNksrTWlmNDRhei9KYTZ1WCtKb3ZEQ1B2MUM0SnVaUGdGeTBDRkdCQldMUlB5a20KT21aSVZJT290STBJWU8rSnU5TlVkYUhtSlBsMzQzS1hsa0E0QzljRnFsNEFFYUZPaXJYaitpNzRwaEd2L1dkTgo0dHFzVVpQejh3MUJiKzVyUkgwSW45SU52enVVcU8wRzJ4RkMvSDY5ZlhudFRsYUdjOFplCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-secret","app.kubernetes.io/part-of":"argocd"},"name":"argocd-secret","namespace":"argocd"},"type":"Opaque"}
    creationTimestamp: "2024-06-30T18:23:47Z"
    labels:
      app.kubernetes.io/name: argocd-secret
      app.kubernetes.io/part-of: argocd
    name: argocd-secret
    namespace: argocd
    resourceVersion: "93643"
    uid: 970c66fc-fc73-43d0-942b-988fd2ddef08
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
